name: manipulator-project
channels:
  - conda-forge
dependencies:
  - gym=0.21.0
  - numpy=1.23.4
  - opencv=4.6.0
  - pillow=9.2.0
  - py-opencv=4.6.0
  - pyglet=1.5.27
  - pymunk=6.3.0
  - python=3.10.6
  - scipy=1.9.3
  - pip:
    - pygame==2.1.2
    - matplotlib
    - einops
    - tqdm
    - attrs
    - loguru
    - seaborn
    - ipdb
    - typer
